name: Lint Pull Request, Merge, and Push

on:
    push:
    pull_request:


jobs:
    build:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4 # Updated to the latest version

            - name: Install Dependencies
              run: npm install

            - name: Run ESLint
              run: npx eslint src/
